import fs from 'fs';
import path from 'path';
import React from 'react';
import ReactDOMServer from 'react-dom/server';
import { StaticRouter } from 'react-router-dom/server';
import { App } from './src/App.jsx';

// Paths relative to project root
const DIST_DIR = path.resolve(process.cwd(), 'dist');
const BASENAME = '/website/'; 

const routes = ['/', '/about'];

export async function prerender() {
  const templatePath = path.join(DIST_DIR, 'index.html');
  
  if (!fs.existsSync(templatePath)) {
    console.error('Error: dist/index.html not found. You must run "npm run build" before prerendering.');
    process.exit(1);
  }
  
  const template = fs.readFileSync(templatePath, 'utf-8');

  for (const url of routes) {
    // 1. Prepare correct router location (must include basename)
    const location = url === '/' 
      ? BASENAME 
      : BASENAME.replace(/\/$/, '') + url;

    // 2. Render App to String
    const appHtml = ReactDOMServer.renderToString(
      <StaticRouter basename={BASENAME} location={location}>
        <App />
      </StaticRouter>
    );

    // 3. Inject into the existing HTML template
    // This preserves the <script> and <link> tags generated by Vite
    const html = template.replace(
      '<div id="root"></div>', 
      `<div id="root">${appHtml}</div>`
    );

    // 4. Save to correct path
    // / -> dist/index.html
    // /about -> dist/about/index.html
    const routePath = url === '/' ? 'index.html' : `${url.replace(/^\//, '')}/index.html`;
    const outputPath = path.join(DIST_DIR, routePath);
    const outputDir = path.dirname(outputPath);

    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, html);
    console.log(`Prerendered: ${url} -> ${outputPath}`);
  }
}

// Run the function
prerender();
