import fs from 'fs';
import path from 'path';
import React from 'react';
import ReactDOMServer from 'react-dom/server';
import { StaticRouter } from 'react-router-dom/server';
import { HelmetProvider } from 'react-helmet-async';
import { App } from './src/App.jsx';
// Import your data logic to calculate routes dynamically
import { processProductData, slugify } from './src/data';
import rawProducts from './src/products.json';

// Paths relative to project root
const DIST_DIR = path.resolve(process.cwd(), 'dist');
const BASENAME = '/'; 

export async function prerender() {
  const templatePath = path.join(DIST_DIR, 'index.html');
  
  if (!fs.existsSync(templatePath)) {
    console.error('Error: dist/index.html not found. You must run "npm run build" before prerendering.');
    process.exit(1);
  }
  
  const template = fs.readFileSync(templatePath, 'utf-8');

  // --- 1. GENERATE DYNAMIC ROUTES ---
  // Process data exactly as the app does to ensure slugs match
  const appData = processProductData(rawProducts);
  
  // Start with static pages
  const routes = ['/', '/about'];

  // Add Collection Pages (e.g., /thundercats/, /wwf/)
  appData.collections.forEach(collection => {
    routes.push(`/${slugify(collection)}/`);
  });

  // Add Product Pages (e.g., /thundercats/lion-o/)
  appData.products.forEach(product => {
    routes.push(`/${product.fullSlug}/`);
  });

  console.log(`🚀 Prerendering ${routes.length} pages...`);

  // --- 2. RENDER EACH PAGE ---
  for (const url of routes) {
    const helmetContext = {};
    
    // Prepare correct router location
    const location = url === '/' 
      ? BASENAME 
      : BASENAME.replace(/\/$/, '') + url;

    // Render App to String
    const appHtml = ReactDOMServer.renderToString(
      <HelmetProvider context={helmetContext}>
        <StaticRouter basename={BASENAME} location={location}>
          <App />
        </StaticRouter>
      </HelmetProvider>
    );

    // Extract Head data (Title, Meta tags) generated by React Helmet
    const { helmet } = helmetContext;
    
    // Inject App HTML
    let html = template.replace(
      '<div id="root"></div>', 
      `<div id="root">${appHtml}</div>`
    );

    // Inject Head Data (SEO titles, descriptions, etc.)
    // We replace the existing <title> and add other meta tags
    const headContent = `
      ${helmet.title.toString()}
      ${helmet.meta.toString()}
      ${helmet.link.toString()}
    `;
    
    // Replace the placeholder title or append to head
    html = html.replace('<title>Loft Loot</title>', headContent);

    // Save to file
    const routePath = url === '/' ? 'index.html' : `${url.replace(/^\//, '')}/index.html`;
    const outputPath = path.join(DIST_DIR, routePath);
    const outputDir = path.dirname(outputPath);

    if (!fs.existsSync(outputDir)) {
      fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, html);
  }
  
  console.log('✅ All pages generated successfully.');
}

prerender();
